(function(o){var g=function(){throw"Synchronous require() is not supported.";};g.unit={};var p="",j,k,q,r=2E4,m,C=document.getElementsByTagName("head")[0],l=Object.prototype.hasOwnProperty;if(function(){for(var a in{hasOwnProperty:!0})return a}()=="hasOwnProperty")var s=function(a,b,d){for(var c in a)l.call(a,c)&&b.call(d,c)};else var y=["isPrototypeOf","hasOwnProperty","toLocaleString","toString","valueOf"],s=function(a,b,d){for(var c in a)l.call(a,c)&&b.call(d,c);for(var e=y.length;e--;)c=y[e],
l.call(a,c)&&b.call(d,c)};var D=function(a,b){for(var d=0;d<a.length;)b.call(null,a[d],d)===!0?a.splice(d,1):d++},z=function(a,b){var d=a.split("/"),b=b||"";b.length&&b.charAt(b.length-1)!="/"&&(b+="/");var c=b.split("/");c.pop();for(var e;e=d.shift();)e!="."&&(e==".."&&c.length&&c[c.length-1]!=".."?c.pop():c.push(e));return c.join("/")},n=g.unit.resolveModuleId=function(a,b){return a.charAt(0)!="."?a:z(a,b)},t=function(a){return a.charAt(0)!="."?p+a+".js":this._resolveModuleId(a,p)+".js"},i=function(a){if(!l.call(j,
a))return null;return j[a]},E=function(a,b){k.push([a.slice(0),b])},B=function(a,b,d){for(var c=[],e=a.length;e--;){var h=n(a[e],d);i(h);u(h)||c.push(h)}c.length?(E(c,function(){b(v(d))}),A(c)):setTimeout(function(){b(v(d))},0)},v=function(a){var b=function(b){var c=n(b,a);if(b=i(c)){if(b.error)throw"Error loading module";}else throw"Module not loaded";if(!b.exports){b.exports={};for(var c=c.substring(0,c.lastIndexOf("/")+1),e=b.injects,h=[],f=0,w=e.length;f<w;f++)e[f]=="require"?h.push(v(c)):e[f]==
"exports"?h.push(b.exports):e[f]=="module"&&h.push(b.module);b.factory.apply(null,h)}return b.exports};b.ensure=function(b,c){B(b,c,a)};if(m!=null)b.main=i(m).module;return b},A=function(a){for(var b=a.length;b--;){var d=a[b];i(d)==null&&(j[d]={},q(d))}},u=function(a){var b={},d=function(a){if(b[a]==!0)return!0;b[a]=!0;a=i(a);if(!a||!a.defined)return!1;else{for(var a=a.deps||[],e=a.length;e--;)if(!d(a[e]))return!1;return!0}};return d(a)},x=function(){for(var a=0;a<k.length;){for(var b=k[a][0],d=k[a][1],
c=0;c<b.length;)u(b[c])?b.splice(c,1):c++;b.length?a++:(k.splice(a,1),d!=null&&setTimeout(d,0))}};q=function(a){var b,d=function(){var b=i(a);if(!b.defined)b.defined=b.error=!0,x()},c=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP"),e=t(a);c.open("GET",e,!0);c.onreadystatechange=function(){if(c.readyState===4)if(clearTimeout(b),c.status==200||c.status===0){for(var h=c.responseText,f=F(h),w=a.substring(0,a.lastIndexOf("/")+1),i={},k=f.length;k--;)f[k]=n(f[k],w);try{i[a]=
o("({fn: function(require, exports, module) {\r\n"+h+"\r\n}})").fn}catch(j){throw j instanceof SyntaxError&&(h="Syntax Error: ",j.lineNumber?h+="line "+(j.lineNumber-581):console.log("GameJs tip: use Firefox to see line numbers in Syntax Errors."),h+=" in file "+e,console.log(h)),j;}g.define(i,f)}else d()};b=setTimeout(d,r);c.send(null)};var F=g.unit.determineShallowDependencies=function(a){for(var b={},d,c=/(?:^|[^\w\$_.])require\s*\(\s*("[^"\\]*(?:\\.[^"\\]*)*"|'[^'\\]*(?:\\.[^'\\]*)*')\s*\)/g;d=
c.exec(a);)d=eval(d[1]),l.call(b,d)||(b[d]=!0);for(c=/(?:^|[^\w\$_.])require.ensure\s*\(\s*(\[("[^"\\]*(?:\\.[^"\\]*)*"|'[^'\\]*(?:\\.[^'\\]*)*'|\s*|,)*\])/g;d=c.exec(a);)for(var e=eval(d[1]),h=e.length;h--;)d=e[h],delete b[d];var f=[];s(b,function(a){f.push(a)});return f},G=function(a){var b=document.createElement("script");b.type="text/javascript";b.src=t(a);var d=!!b.addEventListener,c,e=function(){f(!1)},h=function(){(d||b.readyState=="complete"||b.readyState=="loaded")&&f(i(a).defined)},f=function(f){clearTimeout(c);
d?(b.removeEventListener("load",h,!1),b.removeEventListener("error",e,!1)):b.detachEvent("onreadystatechange",h);if(!f&&(f=i(a),!f.defined))f.defined=f.error=!0,x()};d?(b.addEventListener("load",h,!1),b.addEventListener("error",e,!1)):b.attachEvent("onreadystatechange",h);c=setTimeout(e,r);C.appendChild(b)},H=function(a,b,d){var c={modules:[]},e=["require","exports","module"];typeof a=="object"?(c.deps=b||[],s(a,function(b){var d={id:b};typeof a[b]=="function"?(d.factory=a[b],d.injects=e):(d.factory=
a[b].factory,d.injects=a[b].injects||e);c.modules.push(d)})):(c.deps=b.slice(0),D(c.deps,function(a){a:{for(var b=e.length;b--;)if(e[b]==a){a=b;break a}a=-1}return a>=0}),c.modules.push({id:a,factory:d,injects:b}));return c};g.setModuleRoot=function(a){if(!/^http(s?):\/\//.test(a))var b=window.location.href,b=b.substr(0,b.lastIndexOf("/")+1),a=z(a,b);a.length&&a.charAt(a.length-1)!="/"&&(a+="/");p=a};g.setTimeoutLength=function(a){r=a};g.useScriptTags=function(){q=G};g.def=g.define=function(){for(var a=
H.apply(null,arguments),b=[],d=[],c=a.deps,e=a.modules.length;e--;){var h=a.modules[e],f=h.id,g=i(f);g||(g=j[f]={});g.module={id:f,uri:t(f)};g.defined=!0;g.deps=c.slice(0);g.injects=h.injects;g.factory=h.factory;d.push(g)}for(e=c.length;e--;)f=c[e],g=i(f),(!g||!u(f))&&b.push(f);b.length&&setTimeout(function(){A(b)},0);x()};g.isKnown=function(a){return i(a)!=null};g.isDefined=function(a){a=i(a);return!(!a||!a.defined)};g.ensure=function(a,b){B(a,b,"")};g.run=function(a,b){a=m=n(a,"");g.ensure([a],
function(d){d(a);b!=null&&b()})};g.reset=function(){m=null;j={};k=[];g.define({system:function(){}})};g.reset();window.require=g})(function(o){with(window)return eval(o)});
